repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/chezou/pre-commit-rust
    rev: v0.4.0
    hooks:
      - id: rustfmt
        args: ["--edition=2021"]
